### ISSUE TITLE
RFC：基于 unplugin 设计插件层的 API

### ISSUE THREAD

**Issue by sorrycc** [umijs/mako#1238]
> 名称可能不同，但需要有类似的功能。  
> Updated @ 2024.10.09

好处是，可以复用 unplugin 的生态。

需要新增的 Hook：

- [x] `enforce('pre' | 'post')` #1646
- [x] `buildStart(options) => void`
- [x] `resolveId(source, importer, options) => string | null | false | { id, external?, … }` #1625
- [x] `loadInclude(id) => boolean` #1630
- [x] `transformInclude(id) => boolean` #1639
- [x] `transform(code, id) => { code, ast?, map? } ` #1637
- [x] `buildEnd(error: Error) => void`，修改 generateEnd 加上 error 参数支持 #1644
- [x] `writeBundle()` 无参数 #1650
- [x] `watchChange: (id: string, change: {event: 'create' | 'update' | 'delete'}) => void` #1651

需要新增的 Context：

- [ ] `this.parse(code:string, options) => AST`
- [ ] `this.addWatchFile(id: string)`
- [x] `this.emitFile(assets_only)`
- [x] `this.warn(log: string | {})`
- [x] `this.error(log: string | {})`

注：

- 有些 hook 名和参数的兼容层可以放 JS 里实现

修改 hooks 步骤，

1、plugin 和 plugin_driver 里定义  
2、在需要的地方调用他  
3、binding 层，js_hook 和 js_plugin 里各加一下  
4、在 e2e/fixtures/plugins 里补充用例，然后执行 br test:e2e -- --only plugins 验证  
5、补充文档

参考：  
https://unplugin.unjs.io/guide/

**Comment by afc163** [comment]
> 可以复用 unplugin 的生态。
+10086

**Comment by afc163** [comment]
如何防止 js 插件给速度带来的问题，可能要提供一些性能检测工具，ci 套件和性能最佳实践。
