### ISSUE TITLE
RFC：优化 Mako 命令行

### ISSUE THREAD

**Issue by sorrycc** [umijs/mako#1245]
## 问题

现状是这样。

```
Building with mako for development...
✓ Built in 75ms
Checking...
Hot rebuilt in 1ms
Full rebuilt in 19ms
```

有小伙伴觉得相比竞品过于简洁。除此之外，还有一些其他问题，

- #1243 ，要求日志输出可配 logLevel
- #1233 ，要求独立使用 mako 时有 server 信息输出

这个输出是基于 Umi 使用场景设计的，针对独立使用场景，确实需要再调整下。

## 方案

- [x] 1、去掉「Hot rebuilt in xxx」日志，因为这个功能暂时无效  #1265
- [x] 2、针对独立使用场景提供更多信息，包括 Mako 版本、配置使用情况、DevServer 相关等 #1265

```
Mako v0.5.3

Local:   http://localhost:3000/
Network: http://x.x.x.x:3000/

Building with mako for development...
✓ Built in 75ms

Checking...
Compiled in 19ms
```

- [x] 3、DevServer 在端口冲突时自动探测新的，并给出提示。 #1266

```
Port 3000 is in use, using 3001 instead...
```

- [ ] 4、新增 logLevel api 配置，允许设置为 error 禁用 info 日志信息。

- [x] 5、独立使用时，Dev 阶段，首次构建成功后在浏览器里打开。 #1267
