### ISSUE TITLE
Mako Roadmap

### ISSUE THREAD

**Issue by sorrycc** [umijs/mako#1586]
## v0.9.0

- [x] Upgrade swc to latest
	- #1444

## v0.10.0

- [x] JavaScript transformer plugin

## v0.11.0

- [x] Unplugin compatible plugin API
	- #1238

## v0.12.0

- [ ] Module Federation

## v0.13.0

- [ ] Build fs cache

**Comment by gland2015** [comment]
这个项目怎么感觉就一个人在开发，稳吗，能支持tailwindcss吗

**Comment by lcoder** [comment]
我想找支持tailwindcss

> 这个项目怎么感觉就一个人在开发，稳吗，能支持tailwindcss吗

I also want to find a solution that supports tailwindcss. I looked in the examples directory but didn't see any.
