### ISSUE TITLE
Mako 10.10 RC 发布 TODO

### ISSUE THREAD

**Issue by sorrycc** [umijs/mako#359]
> RC 发布前每周 Review 和调整。

## 大功能

- [ ] Tree Shaking（先做 reexport，小目标是 Webpack 的 1.5 倍） @stormslowly 
  - [x] 提供 Basic Tree Shaking 方案供选择
  - [ ] 内置 Helper 到 Runtime
  - [ ] Optimize 时机提前到 CJS 转换之前
  - [x] 修复 antd styled 组件丢失的问题（优先级高）
  - [x] Tree Shaking 解环的问题
- [ ] Code Splitting @PeachScript 
  - [x] 支持不拆 @stormslowly 
  - [x] 新增平衡型的策略
  - [x] 支持 test 类 webpack 配置（优先级低）
  - [ ] 支持提取 Runtime（优先级低）
- [ ] HMR @sorrycc 
  - [x] Missing 问题 #339 @sorrycc 
  - [x] CSS 热更前序修改不响应的问题 @stormslowly 
  - [ ] Hash 推送值和现有是相同的问题 @stormslowly （不能复现？先 HOLD）
  - [ ] HMR 速度问题 @sorrycc 
  - [ ] Assets 资源热更问题 @sorrycc （优先级低，解法朝着放 module_graph 的方式去解）
  - [x] Copy 功能不支持 watch 因为只改了 index.html @sorrycc 
  - [x] HMR JS&CSS Sorcemap @jiesia 
  - [x] HMR 修改非 React 组件会刷新，但是... #318 @sorrycc 
  - [x] Fast Refresh 识别是否 React 组件的逻辑需要调整（现在是判断是否为 .(j|t)sx） @sorrycc 
  - [ ] 非 HMR 的刷新问题，提供一个服务端的接口（优先级低）
  - [ ] HMR .hotupdate 改个目录比如 node_modules/.mako/hotupdate @HiLanXiao 
  - [x] CSS Modules 的热更失效 @PeachScript #448 
- [x] Runtime
- [x] Less 方案 @jiesia 
- [ ] 性能
  - [ ] Generate 部分加缓存让 HMR 更快（优先级中）
  - [ ] 让更多的地方利用多核（优先级中）

## 小功能

- [x] [调研 Farm 是如何识别一个模块是否为 cjs 模块](https://yuque.antfin.com/yuyuehui.yyh/mglqdw/ho52ic3kca4twftb?singleDoc# ) @goo-yyh 
- [ ] 把 .module.css 以非 css module 的方式引用时，应该报错 
- [x] chunksIdToUrlMap 不需要包含 entry chunk
- [x] https://github.com/umijs/mako/issues/487
- [x] 调研 postcss、babel、webpack 插件的使用情况，比如 overrides.less 的 postcss 功能
- [x] 不支持 extraBabelPlugins，导致 techui2 + antd4 没有样式
- [x] cssChunksIdToUrlMap 里丢失 vendors_x-async.css 相关信息 #501 @PeachScript
- [x] okam 场景下 css 和 less 编译报错时不能正常退出 #499
- [x] less 编译问题「Error evaluating function `fade`: Argument cannot be evaluated to a color」，见 icteg7paxuc51ue5 问题 1
- [ ] 打包支持多 entry（闪蝶需要，主要是 Code Splitting 部分） @PeachScript
- [ ] 不支持 emotion，考虑下要不要支持，见 icteg7paxuc51ue5 问题 3
- [ ] 增加物理缓存和按需编译？没缓存，二次启动不如 MFSU，17591 数量级的 Mako，Dev 启动要 31s。
- [ ] minify 性能优化，在文件级做压缩，可以利用并行，最后合成时只做简单的压缩 @stormslowly 
- [ ] 如果报错代码来自 node_modules 下，或者如果有 --verbose 参数，加个堆栈信息
- [x] 排查一遍 Bigfish 的配置兼容性
- [ ] env replacer 应该要修改为 define
- [ ] 优化现有的拆包策略，要对 runtime 更友好 @PeachScript
- [ ] 需确认 inline-source-map 是否能正常工作，如果可以，配置层需要支持切换到这个
- [x] alias 支持相对路径 #309
- [x] less 编译不支持 alias #483 @sorrycc
- [x] module 的 this 指向不对，应该改成 window/globalThis @goo-yyh 
- [x] #511
- [x] group chunk 可能死循环的问题 @PeachScript 
- [x] 产物里的中文没有转成 ascii code @heden9 
- [ ] 支持 webpack magic comment 生成 async chunk name 文件名 @heden9 
- [ ] 更短的 chunk name #465 （优先级低）
- [x] 配置防御，Review 一遍 Umi 和 Bigfish 的配置，该传的传，不支持的报错，需要支持但还没有支持记 issue 做掉 @sorrycc 
- [x] 检测到按需 externals 的配置，提示报错 @sorrycc
- [x] CSS 被提取之后，模块可以删除 @jiesia 
- [x] 项目验证，人均 1+，参考 https://github.com/umijs/mako/issues/359#issuecomment-1726814998
- [x] @alipay/mako-codemod @hanzebang 
- [x] 实现 auto css modules，兼容老的方式 @Maple0817
- [x] ast to code 提速 #451 @stormslowly 
- [ ] import * as x 值的 break change 问题 #479 @stormslowly 
- [x] bundler-okam 支持 proxy
- [x] less 工作不正常 #436 @jiesia 
- [x] less 支持 theme 主题
- [x] 修复 css/less module 的 load 执行两边的问题（加了个缓存，然后就不需要管他执行几遍了）
- [x] 优化 less，1）npx less 比较慢，应该有更好的方式，2）增加缓存机制，3）... @jiesia 
- [x] pdfjs-dist 卡主 #371 @goo-yyh 
- [x] groupChunk 提速 @PeachScript
- [x] optimizeChunk 提速，参考 tulkun 项目 @PeachScript
- [x] 内置处理 NODE_ENV #439 @HiLanXiao  
- [x] 构建成功但运行报错的包的问题排查 #372 @HiLanXiao 
- [x] mako 需要 node 16+，在 Umi 层和 Mako 层分别做拦截报错 #300 @sorrycc 
- [x] 遇到不支持的语法时主动抛错 #166 @sorrycc 
- [x] 改进 socket server 端口被占时的处理 #399 @goo-yyh 
- [ ] mako：runtime 需要瘦身，1）减尺寸，2）按需挂载 @sorrycc 
- [x] 确认 mako 产物的兼容性问题，包括 css 和 js @sorrycc 
- [ ] 处理配置文件 mako.config.json 读取抛错的场景（优先级低）
- [x] production 模式下默认用 hash id #420 @goo-yyh 
- [x] 产物支持带 Hash
- [ ] 支持 ignore 配置，功能参考 webpack 的 IgnorePlugin @stormslowly 
- [ ] Entry 不支持基于 key 做 output（优先级低） 
- [x] Resolve 报错修复 #358 #284 等 @sorrycc 
- [x] stats 相关报错 #348 @goo-yyh 
- [x] Top Level Await #216 @jiesia 
- [x] CSS 语法错误提示 #357 
- [x] css modules :global 和 :local 的兼容问题 #323 @goo-yyh 
- [x] 启动前清空 output 目录 #380 @goo-yyh 

## 代码组织

- [x] copy 改成插件的实现

## 运营

- [x] Mako x 海阔天空 @PeachScript 

## 业务接入

- [ ] Bigfish @sorrycc 
  - [ ] 新的脚手架 @hanzebang 
  - [ ] 可迁移 Mako 的检测脚本 @hanzebang 
  - [ ] 项目试点（雨燕） @hanzebang 
  - [ ] 项目试点（utm） @jiesia 
  - [ ] 更多项目试点（待定）
  - [ ] Bigfish 本身的性能优化（优先级低）
  - [x] Bigfish 接入 Mako 项目调整
- [ ] Minifish 90%? @stormslowly 
  - [ ] Minifish Compiler 功能通用化 #334 @stormslowly 
  - [ ] 支持通过返回值拿到 output 的内容
- [ ] 闪蝶 @stormslowly 先开个头
  - [x] px2rem #310 @sorrycc
