### ISSUE TITLE
Mako RC 发布计划

### ISSUE THREAD

**Issue by sorrycc** [umijs/mako#528]
里程碑。

- 10.24 发布 RC（暂定）

## 卡点问题

> 不解不能上线。

- 性能问题
	- [x] [ast to code 提速](https://github.com/umijs/mako/issues/451) @辟殊 2023.10.13
	- [x] code splitting 增量编译提速 @辟起 2023.10.13
	- [x] 验证大型项目的 hmr 效果，确认后续 Action（潜在风险）
- Bugfix
	- [x] Less 编译的各种奇怪报错 @云谦
	- [x] [okam 场景下 css 和 less 编译报错时不能正常退出](https://github.com/umijs/mako/issues/499)（花了些时间没找到原因，需要大家的协助） @jiesia
	- [x] gdp/bigscreen_2019 项目问题 3「asset-manifest.json 找不到」修复 @云谦
	- [x] antd 3 + techui 的样式问题 @云谦
	- [x] 一例 CSS 产物顺序问题 @辟起
- Features
	- [x] Umi：调整 overrides.less 方案 @云谦
	- [x] Umi：支持 libraryTarget('umd').library(pkg.name)，解 qiankun plugin + slave 的问题 @云谦
- 严重体验问题
	- [x] [watch mode 下 同时修改两个文件，mako 进入死锁](https://github.com/umijs/mako/issues/515) @jiesia
	- [x] [watch mode 下，删除一个文件，然后重新添加回来不会 full rebuild](https://github.com/umijs/mako/issues/555) @辟殊
	- [x] 热更相关的体验问题
- 流程验证
	- [x] 部署 qiankun 子应用上线（依赖前面 qiankun 相关 feature） @韩泽邦
	- [x] 项目的 Tree Shaking 验证 @辟殊
- 其他新增卡点问题（潜在风险）

## 次要问题

- 性能问题
	- [ ] minify 性能优化，在文件级做压缩，可以利用并行，最后合成时只做简单的压缩 @辟殊
- FEATURE
	- [ ] [支持多 entry 的 Code Splitting](https://github.com/umijs/mako/issues/505) @辟起 （优先级调低，看闪蝶的需求情况）
- 产物性能问题
	- [ ] 优化现有的拆包策略，要对 runtime 更友好 @辟起（优先级调低，目前和 webpack 差别不大）
- 让 mako 更稳定的工程化方案
	- [ ] 基于 commit 的 Benchmark 脚本 @韩泽邦
	- [x] e2e 测试仓库 @韩泽邦 @云谦
	- [x] e2e 测试支持 HMR 测试 @云谦
	- [x] 提取依赖到 core @云谦 @goo-yyh
	- [x] Bigfish to Mako 的 Codemod 完善 @韩泽邦

## 发布前准备

- 再验 10 个项目，要求产出报告文档到语雀仓库 @所有人
	- [x] CoCo/tern-masterapp-coco @云谦
	- [ ] bkhyperautotest/bkhyperautotest @云谦
	- [x] insuranceprod/ins-page-portal-default @辟殊
	- [x] insuranceprod/cityOpen @辟殊
	- [x] zerocode/frontend-view @辟起 （项目太新没有参考价值）
	- [x] antlaw/legal-app-insider @辟起
	- [x] postloan/plcollection-workbench @杰司
	- [ ] PurchasesGroup/IndexAndCommonTool @油油
	- [ ] loanprod/bsiteMerchant @常夜
	- [x] mybank-prod/bk-merchant-saas-main @卫初
- 文档
	- [ ] Mako 介绍 @辟起
	- [ ] 升级构建工具到 Mako @云谦 @韩泽邦
		- 依赖 codemod
		- 升级项目要求
		- 升级步骤
		- FAQ
- [ ] 发布稿（简单点，RC 低调发布吧，高调的等 11 月份的正式发布） @云谦
- [ ] 推广方案 @辟殊

## 参考

https://github.com/umijs/mako/issues/359  
https://github.com/umijs/mako/issues/253
