### ISSUE TITLE
Mako 正式版计划

### ISSUE THREAD

**Issue by sorrycc** [umijs/mako#578]
- 里程碑
	- [x] 11.8 Bigfish 脚手架接入
	- [x] Minifish（通过试验性的配置先上）11.03 决定上不上。
	- [x] 闪蝶: 预计发布时间 11.17 具体节奏 [ref](https://github.com/umijs/mako/issues/578#issuecomment-1780243873)
	- [ ] 11.23 代码层的发布（含 Bigfish 4.1）
	- [ ] 11.24 正式发布
- Bugfix
	- [x] [[Mako 问题 20231025]]
	- [x] https://github.com/umijs/mako/issues/555
	- [x] CloudIDE 下的 HMR 问题
- 稳定性
	- [x] mako-e2e 仓库补充用例，目前 20+
	- [x] mako-e2e 支持 dev 和 hmr 的用例测试方式
		- [[Mako x HMR 用例]]
	- [x] 跑完 1900+ Bigfish 4 项目，修复后重复跑错误的
	- [ ] 重新跑 1800+ npm 包的不同版本
	- [x] 提升 tree-shaking 稳定性，几个思路包括，项目验证、测试用例、用脚本验真实项目
	- [x] 提升 resolve 稳定性
	- [x] Mako E2E 支持 build 后验 runtime 的场景和出错捕获场景
- 功能开发
	- [x] bwmAutoExternals @辟起
	- [x] Worker @杰司
	- [x] transformImport 的配置转换 @辟起
	- [x] Platform: Node @辟起
	- [ ] [支持 frag 和 vert 文件（解法：支持通过 loader 配置扩展）](https://github.com/umijs/mako/issues/599)
- 体验优化
	- [ ] [build 阶段相同的错误信息不要重复出现](https://github.com/umijs/mako/issues/639)
- 性能优化
	- [ ] HMR Full Rebuilt 拆到子线程 @辟殊
	- [ ] Tree Shaking 产物优化，参考 mako-e2e 里带 .failed 的用例 @辟殊 @油油
	- [x] [perf: transform_in_generate 优化](https://github.com/umijs/mako/issues/551) @油油
	- [x] PERF: less 改用 napi 的方式调函数，lessc 启动多用了 32.3s  
	- [ ] 优化 runtime，现在很多不是按需的
	- [ ] optimizePackageImports @杰司
- 业务推广
	- TODO
- 业务场景
	- [x] Bigfish
	- [x] Minifish
	- [x] 闪蝶
- Bigfish
	- [x] 脚手架接入，启动时给明显提示
	- [x] bundler-okam 支持 onDevCompileDone
	- [x] 调整监控，实时检测 Mako 项目的接入情况和错误信息
- 文档相关
	- [x] Bigfish + Mako 文档
- TODO
	- Bundle CSS 合并时添加注释，需要知道哪部分来自哪个文件
