### ISSUE TITLE
Mako Next

### ISSUE THREAD

**Issue by sorrycc** [umijs/mako#671]
## 里程碑

- 0.2.0 @ 2023.12.15
	- [ ] Feat: Tree Shaking 降低 10% #727 （1） @辟殊
	- [x] Feat: Require with Expression #719 @辟起
	- [ ] Feat: Code Splitting 支持多 Entry #505 （1） @近西 @辟起
	- [x] Feat: Runtime 产物优化，按需载入 @云谦
	- [x] Bug: Git Checkout 和 Git Clean 在多平台的问题修复 @云谦
	- [ ] ~~Chore: build 阶段相同的错误不要重复出现 #639 @云谦~~
	- [x] Refact: Build @云谦
	- [x] Refact: 迁移 Mako E2E 回 Mako 仓库 @云谦
	- [x] Docs: 接口和配置文档 @云谦
- 0.3.0 @ 2023.12.29
	- [x] Feat: Tree Shaking 降低 10% #727 （2） @辟殊
		- 功能包括：reexport 的 Tree Shaking
		- 目前 6%
	- [x] Cache 针对 Build 可以去掉 @卫初
	- [x] Feat: Code Splitting 支持多 Entry #505 （2） @近西 @辟起
	- [ ] Tree Shaking 支持 dev（1） @辟起
	- [ ] Feat: 支持 Styled Component Babel 插件的功能 @油油
	- [x] Feat: optimizePackageImports @杰司 @云谦
		- TODO：export *
	- [x] try…catch 下的 require 在 dev 时不应该显示出来 @云谦
	- [x] HMR 在 Node 场景下不应注入 @云谦
	- [x] Father 接入 RFC @辟起
	- [x] Dumi 接入 RFC @辟起
	- [ ] 设计插件机制 @云谦
	- [ ] ~~改善性能（1） @云谦~~
	- [x] targets: { ie: 11 } 后 umi 最简项目会出错
	- [x] 完善配置项，比如 tree_shake 改成 tree_shaking 等，详见配置文档 @辟起
- 0.3.0 @ 2024.01.12
	- [x] Mako 监控数据 @辟起
	- [ ] 写个脚本做监控 @云谦
	- [ ] Tree Shaking 相关
		- 降了 2-3%
		- 110% - 105%
		- [x] 符号替换
		- side effect 判定过于保守（比如识别 pure 注释）
		- 模块合并
		- 导出混淆
	- [ ] Tree Shaking 支持 dev（2） @辟起
	- [ ] Feat: 支持 Styled Component Babel 插件的功能（2） @油油
	- [x] 设计插件机制（2） @云谦
	- [x] HMR 相关用例 X2 @云谦 （一个修复，另一个已不能复现）
	- [ ] 更多 Mako 广告位和脚手架接入 @云谦
- 0.4.0 @ 2024.01.26（延到 2024.01.29）
	- [ ] Minifish 和闪蝶的 Mako 监控 @辟起
	- [x] SWC 升级 @油油
	- [ ] Feat: 支持 Styled Component Babel 插件的功能（3） @油油
	- [ ] Tree Shaking 支持 dev（3） @辟起
	- [x] Tree Shaking：Skip Modules 问题修复 @辟殊
	- [ ] Tree Shaking：模块合并 RFC @辟殊
	- [x] 完善 Node 支持 @云谦
	- [ ] Tree Shaking 对比工具 @油油
	- [x] Benchmark 和 Tree Shaking 的脚本 @云谦
	- [x] Smallfish 基础 RFC @云谦
- 0.5.0 @ 2024.02.07（二十八）
	- [ ] forkTSChecker 调研和实现 @桃树
	- [ ] Analyze @卫初
	- [ ] 虚拟 Entry 和虚拟文件 @云谦
	- [ ] HMR Client 支持定制 @云谦
	- [ ] Tree Shaking 支持 dev（4） @辟起
	- [ ] Tree Shaking：模块合并 RFC（2） @辟殊
	- [ ] Smallfish RFC 完善和开发 @云谦 @辟起
	- [ ] Tree Shaking 对比工具（2） @油油
	- [ ] 验证下 Worker 场景并完善方案，确保一些场景（比如 pdfjs-dist）可用
	- [ ] 设计插件机制（3）完善 @云谦
- 0.x
	- [ ] Module > Program
		- TSX 类型转换
		- AST Module(ESM), Script(CJS) > PROGRAM
	- [ ] Feat: Dev 挪到新的线程 @油油
	- [ ] Feat: condition folding 支持 typeof require 等 #673 ==求认领==
	- [ ] Feat: 支持 Link 调试外部包，思路是 build 完成后分析非项目目录的文件，额外做 Watch，配置开启 ==求认领==
	- [ ] Feat: Assets 资源支持热更 ==求认领==
	- [ ] Chore: 补充 minifish 的 E2E 用例 @辟殊
	- [ ] Feat: Bundless 支持 Watch 模式 @辟殊

## 功能

- [x] 多 entry @近西
- [ ] optimizePackageImports @杰司
- [x] Less 编译提速 @云谦
- [ ] Tree Shaking 打磨 @辟殊 + 更多人
- [ ] Tree Shaking 支持 JSON @辟殊 + 更多人
- [ ] Tree Shaking 支持 CJS @辟殊 + 更多人
- [ ] Tree Shaking 支持 Dev @辟殊 + 更多人
- [ ] Code Splitting 对 Runtime 更友好 @辟起
- [x] 设计 Plugin 机制  
- [x] 设计 okam 接口层 @云谦
- [x] 支持 emotion @卫初
- [ ] PERF：Scope Hoisting  
- [ ] PERF：FS Cache  
- [ ] PERF：按需编译  
- [x] Magic Comment  
- [ ] forkTSChecker  
- [ ] ignoreMomentLocale  
- [ ] Case Sensitive  
- [ ] Analyze  
- [ ] Output ESM/CJS/IIFE  
- [ ] 调研 [osx_resolver](https://github.com/web-infra-dev/oxc/blob/main/crates/oxc_resolver/README.md)，尝试接入
- [ ] IDEA：支持浏览器里跑 Mako  
- [ ] ESMi？
- [ ] Mako x AI?

## 业务

。

[[Mako 业务落地计划]]

## 推广

。
