### ISSUE TITLE
RFC：性能和 Tree Shaking 效果的 Benchmark 脚本

### ISSUE THREAD

**Issue by sorrycc** [umijs/mako#892]
**问题：**

目前没有这部分的工具，同时内置的 with-antd 虽然依赖较多，但也只能代表依赖多的场景，而我们做的优化（包括性能和产物尺寸）可能在一个场景下有提升，但在另一个场景下反而降低。所以，我们需要一个更大范围的性能和 Tree Shaking 效果检测的 Benchmark 方案。

**方案：**

1、新增一个仓库来跑 Benchmark  
2、两个维度，1）支持配置 N 个用于做 Benchmark 的仓库，仓库来源于内部之前找出来的列表里的 10 个分布点，再加一些典型项目（比如 yuyanAssets、with-antd、脚手架和 ant-design-pro），这个项目需通过 lock 文件锁定依赖，确保每次构建的内容是相同的，2）支持多个 Mako 版本，版本也可以来源于不同的 Mako Commit，或者本地路径（用于本地做 latest 的 Benchmark）。  
3、支持用来验证某些特性的效果，比如在跑之前修改 mako.config.json 的配置。

BONUS：支持 mako 和其他构建工具的 Benchmark 对比。  
BONUS：加个可视化大图，包含每个版本的变化，找个合适的图表来展现。

**命令行：**

```bash
# 基于配置初始化仓库和 Mako 依赖
$ npm run bootstrap
# 或者分开执行
$ npm run bootstrap:projects
$ npm run bootstrap:mako

# 执行 benchmark
$ npm run benchmark
# 支持 --force 忽略缓存（注：耗时会很长）
$ npm run benchmark -- --force
# 只跑特定 mako 版本和制定项目的 Benchmark
$ npm run benchmark -- --project AAA --mako BBB
```

**准备：**

1、在仓库里通过 npm prefix 的方式安装 n 个 mako 依赖  
2、支持配置额外的 mako 地址，用于支持本地 latest 的 mako  
3、准备 n 个（10 +）典型的仓库地址

**实现：**

1、检查缓存，跑过的不重复跑，除非加 --force  
2、先循环 mako 版本列表，再循环仓库地址列表  
3、做一些前置动作，1）一些 assert，比如仓库是否 ready，是否有依赖，2）清空 dist 目录和缓存，3）检查 CPU LOAD，超过 30% 抛错  
4、用某个 mako 版本跑某个仓库，跑 4 次，记录结果，包含产物尺寸和速度的数组、中位数和平均值，速度包含 Bigfish 整体速度（暂时用不到）和只 Mako 消耗的时间  

结果的数据结构。

```js
[
  {
    makoInfo: { version?, path?, commit? },
    data: [
      {
        projectInfo,
        size: {
          average: { js, css },
          median: { js, css },
          details: [
            { js, css, ... },
          ],
        },
        time: {
          average: { mako, bigfish },
          median: { mako, bigfish },
          details: [
            { mako, bigfish },
          ],
        },
      },
    ],
  },
  size: {
    average: { js, css },
    median: { js, css },
  },
  time: {
    average: { mako, bigfish },
    median: { mako, bigfish },
  },
]
```

报告格式。

```
Version: x, Path: x
  Time: 123s ± 21s, 3.90 ± 0.03 times faster/slower
  Size: 1234Mb, 3.90 times bigger/smaller

Version: x, Path: x
  Time: 123s ± 21s, 3.90 ± 0.03 times faster/slower
  Size: 1234Mb, 3.90 times bigger/smaller

...
```

配置文件为 `config.json`，格式如下。projects 存于 `projects` 目录下。

```js
{
  "projects": [
    "a",
    "b"
  ],
  "mako": [
    // 支持版本
    "0.1.0",
    // 支持 commit
    "7c443e8",
    // 支持路径
    "/path/to/bundler-mako"
  ]
}
```

**TODO：**

- [x] 建仓库 https://github.com/umijs/mako-benchmark
- [x] 整理项目列表
- [x] 整理 Mako 版本列表
- [x] 完成 bootstrap 命令
- [x] 完成 benchmark 命令
